version: '3.7'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/upvtc-course-timetabler
        ports:
            - 8000:8000
        environment:
            - DEBUG=1
            - SQL_ENGINE=django.db.backends.postgresql
            - SQL_HOST=db
            - SQL_PORT=5432
        env_file: .config/web.env
        depends_on:
            - db

    db:
        image: postgres:11.5-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: .config/db.env

volumes:
    postgres_data:
